SELECT II.ITEM_ID, II.ITEM_NAME, II.RARITY FROM ITEM_INFO AS II 
WHERE II.ITEM_ID NOT IN (SELECT DISTINCT IT.PARENT_ITEM_ID FROM ITEM_TREE AS IT WHERE IT.PARENT_ITEM_ID IS NOT NULL) # 조건문
ORDER BY ITEM_ID DESC;