/*
FOOD_PRODUCT와 FOOD_ORDER 테이블에서 조인하여 생산일자가 2022년 5월인 식품들을 조회합니다.
*/
SELECT P.PRODUCT_ID, P.PRODUCT_NAME, (SUM(O.AMOUNT * P.PRICE)) AS TOTAL_PRICE FROM FOOD_PRODUCT AS P
JOIN FOOD_ORDER AS O ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE O.PRODUCE_DATE LIKE '2022-05%'
/*
식품별로 매출을 합산하여 TOTAL_PRICE 열에 표시합니다.
*/
GROUP BY P.PRODUCT_ID
/*
총매출을 기준으로 내림차순 정렬하고, 총매출이 같은 경우 식품 ID를 기준으로 오름차순 정렬합니다.
*/
ORDER BY TOTAL_PRICE DESC, PRODUCT_ID ASC;