SELECT 
DATE_FORMAT(O.SALES_DATE, '%Y') AS YEAR, 
DATE_FORMAT(O.SALES_DATE, '%m') AS MONTH, 
U.GENDER,
COUNT(DISTINCT O.USER_ID) AS USERS # 동일한 날짜, 회원 ID, 상품 ID 조합에 대해서는 하나의 판매 데이터만 존재합니다. ➡️ 중복제거 DISTINCT
FROM ONLINE_SALE AS O 
JOIN USER_INFO AS U ON O.USER_ID = U.USER_ID
WHERE U.GENDER IS NOT NULL
GROUP BY YEAR, MONTH, U.GENDER 
ORDER BY YEAR, MONTH, U.GENDER 