SELECT P.PRODUCT_ID, P.PRODUCT_NAME, (SUM(O.AMOUNT * P.PRICE)) AS TOTAL_PRICE FROM FOOD_PRODUCT AS P
JOIN FOOD_ORDER AS O ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE O.PRODUCE_DATE LIKE '2022-05%'
GROUP BY P.PRODUCT_ID
ORDER BY TOTAL_PRICE DESC, PRODUCT_ID ASC;