# 서브 쿼리
SELECT PRODUCT_ID,	PRODUCT_NAME,	PRODUCT_CD,	CATEGORY, PRICE FROM FOOD_PRODUCT
WHERE PRICE = (SELECT MAX(PRICE) FROM FOOD_PRODUCT);

# 가격 기준으로 내림차 순 정렬해서 LIMIT 1을 사용하여 가장 가격이 높은 데이터 반환
SELECT * FROM FOOD_PRODUCT
ORDER BY PRICE DESC
LIMIT 1;