SELECT M.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') FROM REST_REVIEW AS R
JOIN MEMBER_PROFILE AS M ON R.MEMBER_ID = M.MEMBER_ID
WHERE M.MEMBER_ID = (
    SELECT MEMBER_ID 
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(*) DESC
    LIMIT 1
) 
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC;


