SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME FROM FOOD_PRODUCT
WHERE PRICE IN (SELECT MAX(PRICE) FROM FOOD_PRODUCT GROUP BY CATEGORY) AND CATEGORY IN ('과자', '국', '김치', '식용유')
# max로 조회하면 해당 컬럼에 대한 값만 나올뿐 행 전체가 나오지 않는다. 그래서 서브 쿼리로 걸러주고 조회해야한다.
ORDER BY MAX_PRICE DESC;
